import path from 'path'
import fs from 'fs'
import glob from 'glob'

/**
 * Script for automatically generating a file which has a series of `require` statements for
 * importing JSON contract artifacts. We do this to preserve browser compatibility.
 *
 * Reads forge compilation output from forge-artifacts/ (Foundry artifact format).
 */

/** Sanitize a string to a valid JavaScript identifier. */
function toVarName(s: string): string {
    return s.replace(/[^a-zA-Z0-9_$]/g, '_')
}

const main = async () => {
    const contractArtifactsFolder = path.resolve(
        __dirname,
        `../forge-artifacts`
    )

    const artifactPaths = glob
        .sync(`${contractArtifactsFolder}/**/**.json`)
        .filter((match) => {
            if (match.endsWith('.dbg.json')) return false
            if (match.includes('.t.sol/')) return false
            if (match.includes('/build-info/')) return false
            return true
        })

    // Build a map: contractName → list of paths, to detect duplicates.
    const byContractName = new Map<string, string[]>()
    for (const artifactPath of artifactPaths) {
        const fileName = path.basename(artifactPath, '.json')
        const names = byContractName.get(fileName) || []
        names.push(artifactPath)
        byContractName.set(fileName, names)
    }

    // Assign a unique JS identifier to each artifact path.
    // For duplicate contract names, use the full relative directory path as a qualifier.
    const assignedVars = new Map<string, string>()
    for (const [contractName, paths] of byContractName.entries()) {
        if (paths.length === 1) {
            assignedVars.set(paths[0], toVarName(contractName))
        } else {
            // Multiple files share the same contract name – qualify by full directory path.
            for (const p of paths) {
                const relDir = path.relative(contractArtifactsFolder, path.dirname(p))
                const varName = toVarName(relDir + '/' + contractName)
                assignedVars.set(p, varName)
            }
        }
    }

    const importStmts = artifactPaths.map((artifactPath) => {
        const varName = assignedVars.get(artifactPath)!
        const pattern = /\\/g
        const relPath = path.relative(__dirname, artifactPath).replace(pattern, '/')
        return `
        let ${varName}
        try {
          ${varName} = require('${relPath}')
        } catch {}
        `
    }).join('\n')

    const mapEntries = artifactPaths.map((artifactPath) => {
        const varName = assignedVars.get(artifactPath)!
        // Key by both the simple contract name (for backward compat) and the
        // fully-qualified path-based name (guaranteed unique).
        const fileName = path.basename(artifactPath, '.json')
        const relDir = path.relative(contractArtifactsFolder, path.dirname(artifactPath))
        const fullKey = toVarName(relDir) + '/' + fileName
        return `${JSON.stringify(fullKey)}: ${varName}`
    }).join(',\n')

    const content = `
    /* eslint-disable @typescript-eslint/no-var-requires, no-empty */
    /*
    THIS FILE IS AUTOMATICALLY GENERATED.
    DO NOT EDIT.
    Generated from forge-artifacts/ (Foundry compilation output).
    */
    ${importStmts}

    export const getContractArtifact = (name: string): any => {
      return {
        ${mapEntries}
      }[name]
    }
    `

    fs.writeFileSync(
        path.resolve(__dirname, `../src/contract-artifacts.ts`),
        content
    )
}

main()
