FROM rust:1.70 as builder

COPY ./l2-contracts /l2-contracts

WORKDIR /l2-contracts
RUN cd app && cargo build --release

FROM ubuntu:22.04 as app
COPY --from=builder /l2-contracts/app/target/release/app /

CMD ["./app"]