version: '3.8'

services:

  staking-oracle:
    image: morph-staking-oracle
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      # Note that you must index goerli with INDEXER_BEDROCK=false first, then
      # reindex with INDEXER_BEDROCK=true or seed the database
      - STAKING_ORACLE_BUILD_ENV=dev
      - STAKING_ORACLE_L1_ETH_RPC=${L1_ETH_RPC}
      - STAKING_ORACLE_RECORD_PRIVATE_KEY=${RECORD_PRIVATE_KEY}
      - STAKING_ORACLE_L2_ETH_RPC=http://morph-geth-0:8545
      - STAKING_ORACLE_L2_TENDERMINT_RPC=http://node-0:26657
      - STAKING_ORACLE_L2_WS_ENDPOINT=http://node-0:26656
      - STAKING_ORACLE_ROLLUP=${MORPH_ROLLUP:-0x6900000000000000000000000000000000000010}
      - STAKING_ORACLE_LOG_FILENAME=staking-oracle.log
      - STAKING_ORACLE_LOG_FILE_MAX_SIZE=100 #MB
      - STAKING_ORACLE_LOG_FILE_MAX_AGE=7 #day
      - STAKING_ORACLE_LOG_COMPRESS=true
      - STAKING_ORACLE_METRICS_SERVER_ENABLE=true
    ports:
      - 6060:6060
