[package]
name = "prover-executor-host"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
morph-da-encoder-core = { workspace = true }
anyhow = { workspace = true }
c-kzg = { workspace = true }
prover-primitives = { workspace = true }
prover-executor-client = { workspace = true }
prover-storage-rpc = { workspace = true }
prover-executor-core.workspace = true
prover-mpt = { workspace = true }
revm = { workspace = true }
alloy-provider = { workspace = true }
alloy-network = { workspace = true }
alloy-rpc-types = { workspace = true }
alloy-rpc-types-debug = { workspace = true }
alloy-primitives = { workspace = true }
alloy-consensus.workspace = true
reth-trie.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
log = { workspace = true }
morph-rpc = { workspace = true }
morph-primitives.workspace = true

[dev-dependencies]
tokio = { workspace = true }
