#!/bin/bash

# Clean script to reset the network to initial state
# Removes all generated files from generate-genesis and docker compose data

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

echo "=== Cleaning Network Data ==="

cd "$PROJECT_DIR/.."

# Stop and remove only layer1 containers
echo "Stopping and removing layer1 containers..."
docker compose -f docker-compose-4nodes.yml stop layer1-el layer1-cl layer1-vc 2>/dev/null || true
docker compose -f docker-compose-4nodes.yml rm -f layer1-el layer1-cl layer1-vc 2>/dev/null || true

# Remove layer1 volumes
echo "Removing layer1 volumes..."
docker volume rm docker_layer1-el-data docker_layer1-cl-data docker_layer1-vc-data 2>/dev/null || true

# Remove generated genesis files
echo "Removing generated genesis files..."
if [ -d "layer1/genesis" ]; then
    # Remove all generated genesis files - everything in genesis/ is generated by generate-genesis.sh
    # These files are regenerated each time generate-genesis.sh runs
    rm -rf layer1/genesis/genesis.json
    rm -rf layer1/genesis/genesis.ssz
    rm -rf layer1/genesis/config.yaml
    rm -rf layer1/genesis/metadata
    rm -rf layer1/genesis/parsed
    rm -rf layer1/genesis/network-configs
    rm -rf layer1/genesis/jwt
    # Remove all other generated files from ethereum-genesis-generator
    rm -f layer1/genesis/*.json
    rm -f layer1/genesis/*.yaml
    rm -f layer1/genesis/*.txt
    rm -f layer1/genesis/*.ssz
    echo "✓ Genesis files removed"
fi

# Remove generated configs (but keep template)
echo "Removing generated config files..."
if [ -d "layer1/configs" ]; then
    rm -f layer1/configs/values.env
    rm -f layer1/configs/additional-contracts.json
    echo "✓ Config files removed (template preserved)"
fi

# Remove VC slashing protection database (if exists)
echo "Removing VC slashing protection database..."
if [ -d "layer1/keystores/layer1" ]; then
    # Remove slashing protection database but keep keys and secrets
    find layer1/keystores/layer1 -name "*.db" -o -name "*.sqlite" -o -name "*.sqlite3" | xargs rm -f 2>/dev/null || true
    find layer1/keystores/layer1 -type d -name "slashing_protection" -exec rm -rf {} + 2>/dev/null || true
    echo "✓ VC slashing protection database removed"
fi

# Remove any remaining data directories
echo "Removing data directories..."
rm -rf data/ 2>/dev/null || true

# Clean up any docker volumes that might remain
echo "Cleaning up Docker volumes..."
docker volume ls | grep -E "simple-ethereum-network|layer1-" | awk '{print $2}' | while read volume; do
    docker volume rm "$volume" 2>/dev/null || true
done

echo ""
echo "=== Cleanup Complete ==="
echo ""
echo "Removed:"
echo "  - Generated genesis files (genesis.json, genesis.ssz, config.yaml, metadata/, parsed/)"
echo "  - Generated config files (values.env, additional-contracts.json)"
echo "  - Docker containers and volumes"
echo "  - Data directories"
echo ""
echo "Preserved:"
echo "  - Configuration templates (layer1/configs/values.env.template)"
echo "  - JWT secret (layer1/jwt/jwtsecret)"
echo "  - Keystores (layer1/keystores/)"
echo "  - Docker Compose file (docker-compose-4nodes.yml)"
echo ""
echo "You can now run 'make generate' and 'make start' again to create a fresh network."

