FROM sp1-base:latest

COPY . /app
WORKDIR /app
RUN cd bin/host && RUST_LOG=info TRUSTED_SETUP_4844=../../configs/4844_trusted_setup.txt RUSTFLAGS="-C target-feature=+avx2,+avx512f" cargo run --features use-native-gnark --release -- --block-path ../../testdata/mainnet_batch_traces_l1.json --prove