FROM rust:1.70.0 as builder

COPY --from=golang:1.20 /usr/local/go/ /usr/local/go/
ENV PATH="/usr/local/go/bin:${PATH}"

COPY . /prover
WORKDIR /prover

RUN cargo build --release
RUN cp `find ./target/release/ | grep libzktrie.so` /

FROM ubuntu:22.04 as app
COPY --from=builder /prover/target/release/prover_server /
COPY --from=builder /libzktrie.so /usr/local/lib/
RUN echo "/usr/local/lib" >> /etc/ld.so.conf && ldconfig -v

CMD ["./prover_server"]