FROM sp1-base:latest

RUN cargo prove --version

ARG GO_VERSION=1.22
RUN wget https://github.com/anylots/golangTemp/blob/main/go1.22.1.linux-amd64.tar.gz
RUN tar -C /usr/local -xzf go1.22.1.linux-amd64.tar.gz
RUN rm go1.22.1.linux-amd64.tar.gz
ENV PATH="/usr/local/go/bin:${PATH}"

COPY . /app
WORKDIR /app
RUN cd tests/algebra/client && cargo prove build

RUN cd tests/algebra/host && RUST_LOG=debug RUST_BACKTRACE=full cargo run --release