version: '3.4'

volumes:
  plonk_circuits:

services:
  sp1-test:
    build:
      context: .
      dockerfile: Dockerfile.sp1-test
    image: sp1-test:latest
    volumes:
    - /data/develop/sp1-apps/morph/prover/app/build:/root/.sp1/circuits/v1.3.0-rc2-scroll
    - /data/develop/sp1-apps/morph/prover/app/proof:/root/data/proof
    restart: no
    container_name: 'sp1-test'
    command: >
      ./algebra-host
    ports:
      - "3030:3030"
    environment:
      - RUST_LOG=info
      - PROOF_DIR=/root/data/proof
