ARG GO_VERSION=1.24.0
FROM golang:${GO_VERSION}-bookworm AS go-toolchain

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update --fix-missing \
    && apt-get install --yes --no-install-recommends \
        ca-certificates \
        build-essential \
        curl \
        docker.io \
        git \
        libclang-dev \
        libssl-dev \
        llvm \
        pkg-config \
        wget \
        protobuf-compiler \
        libprotobuf-dev \
    && rm -rf /var/lib/apt/lists/*

# Install Rust
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
ENV PATH="/root/.cargo/bin:${PATH}"
ENV CARGO_HOME=/root/.cargo
RUN rustup install 1.95.0
RUN rustup default 1.95.0
RUN rustup component add llvm-tools --toolchain 1.95.0

# Install Golang
COPY --from=go-toolchain /usr/local/go /usr/local/go
ENV PATH="/usr/local/go/bin:${PATH}"
