global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  # L1 execution layer
  - job_name: 'l1-el'
    static_configs:
      - targets: ['layer1-el:9001']

  # L1 consensus layer
  - job_name: 'l1-cl'
    static_configs:
      - targets: ['layer1-cl:5054']

  # L2 morph nodes (tendermint prometheus metrics on port 26660)
  - job_name: 'morph-node'
    static_configs:
      - targets:
          - 'node-0:26660'
          - 'node-1:26660'
          - 'node-2:26660'
          - 'node-3:26660'
          - 'sentry-node-0:26660'
          - 'sentry-node-1:26660'
        labels:
          service: 'morph-node'

  # L2 execution engines (geth metrics on port 6060)
  - job_name: 'morph-geth'
    static_configs:
      - targets:
          - 'morph-el-0:6060'
          - 'morph-el-1:6060'
          - 'morph-el-2:6060'
          - 'morph-el-3:6060'
          - 'sentry-el-0:6060'
          - 'sentry-el-1:6060'
        labels:
          service: 'morph-geth'
