#!/bin/sh
# Assemble and insert a block via Engine API (authrpc :8551, JWT-based)
# - Run from local-test directory (relative paths only)
# - Requires: curl, openssl, jq

set -e

# Endpoints
HTTP_RPC="${HTTP_RPC:-http://127.0.0.1:8545}"
AUTH_RPC="${AUTH_RPC:-http://127.0.0.1:8551}"

# JWT secret path (hex string, usually generated by run-l2-exec-only.sh)
JWT_SECRET_PATH="${JWT_SECRET_PATH:-./jwt-secret.txt}"

require() { command -v "$1" >/dev/null 2>&1 || { echo "ERROR: $1 not found" >&2; exit 1; }; }
require curl
require openssl
require jq

# Read hex secret and normalize (strip 0x and whitespace)
if [ ! -f "$JWT_SECRET_PATH" ]; then
  echo "ERROR: JWT secret file not found at $JWT_SECRET_PATH" >&2
  exit 1
fi
SECRET=$(tr -d '\n\r\t ' < "$JWT_SECRET_PATH")
SECRET=${SECRET#0x}

# Build JWT Bearer token per Engine API spec (HS256, claims: { iat: now })
H_B64=$(printf '{"alg":"HS256","typ":"JWT"}' | openssl base64 -A | tr '+/' '-_' | tr -d '=')
IAT=$(date +%s)
P_B64=$(printf '{"iat":%s}' "$IAT" | openssl base64 -A | tr '+/' '-_' | tr -d '=')
SIG=$(printf '%s.%s' "$H_B64" "$P_B64" | \
  openssl dgst -binary -sha256 -mac HMAC -macopt hexkey:$SECRET | \
  openssl base64 -A | tr '+/' '-_' | tr -d '=')
TOKEN="$H_B64.$P_B64.$SIG"

# Get next block number (current + 1)
CUR_HEX=$(curl -s "$HTTP_RPC" -H 'Content-Type: application/json' \
  -d '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":1}' | jq -r '.result')
if [ -z "$CUR_HEX" ] || [ "$CUR_HEX" = "null" ]; then
  echo "ERROR: failed to fetch current block number from $HTTP_RPC" >&2
  exit 1
fi
CUR_NOX=${CUR_HEX#0x}
NEXT_DEC=$((16#$CUR_NOX + 1))
NEXT_HEX=$(printf '0x%X' "$NEXT_DEC")

# Assemble L2 block (engine_assembleL2Block) using txpool contents
ED_RESP=$(curl -s "$AUTH_RPC" \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer $TOKEN" \
  -d '{"jsonrpc":"2.0","method":"engine_assembleL2Block","params":[{"number":"'"$NEXT_HEX"'","transactions":[]}],"id":2}')
ED=$(printf '%s' "$ED_RESP" | jq -c '.result')
if [ -z "$ED" ] || [ "$ED" = "null" ]; then
  echo "ERROR: assemble failed. Raw response:" >&2
  echo "$ED_RESP" >&2
  exit 1
fi

# Insert new block (engine_newL2Block)
NEW_RESP=$(curl -s "$AUTH_RPC" \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer $TOKEN" \
  -d '{"jsonrpc":"2.0","method":"engine_newL2Block","params":['"$ED"',null],"id":3}')
echo "$NEW_RESP"

# Show latest block number
curl -s "$HTTP_RPC" -H 'Content-Type: application/json' \
  -d '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":4}'