// SPDX-License-Identifier: MIT
pragma solidity =0.8.23;

/**
 * @title Types
 * @notice Contains various types used throughout the Morph contract system.
 */
library Types {
    /**
     * @notice Struct representing a deposit transaction (L1 => L2 transaction) created by an end
     *         user (as opposed to a system deposit transaction generated by the system).
     *
     * @custom:field queueIndex     Index of the transaction.
     * @custom:field gas            Gas limit of the transaction.
     * @custom:field to             Address of the recipient of the transaction.
     * @custom:field value          Value to send to the recipient.
     * @custom:field data           Data of the transaction.
     * @custom:field sender         Address of the sender of the transaction.
     */
    struct L1MessageTx {
        uint64 queueIndex;
        uint64 gas;
        address to;
        uint256 value;
        bytes data;
        address sender;
    }

    /**
     * @notice Struct representing a withdrawal transaction.
     *
     * @custom:field nonce    Nonce of the withdrawal transaction
     * @custom:field sender   Address of the sender of the transaction.
     * @custom:field target   Address of the recipient of the transaction.
     * @custom:field value    Value to send to the recipient.
     * @custom:field gasLimit Gas limit of the transaction.
     * @custom:field data     Data of the transaction.
     */
    struct WithdrawalTransaction {
        uint256 nonce;
        address sender;
        address target;
        uint256 value;
        uint256 gasLimit;
        bytes data;
    }

    /**
     * @notice Struct representing a sequencer information.
     *
     * @custom:field addr   Address of the sequencer.
     * @custom:field tmKey  Tendermint key(ED25519) of the seuqencer.
     * @custom:field blsKey BLS key of the seuqencer.
     */
    struct SequencerInfo {
        address addr;
        bytes32 tmKey;
        bytes blsKey;
    }

    /**
     * @notice BatchInfo representing a batch.
     *
     * @custom:field submitter      batch submitter
     * @custom:field startBlock     batch start block
     * @custom:field endBlock       batch end block
     * @custom:field rollupTime     batch rollup time
     * @custom:field maxChunks      max chunks
     */
    struct BatchInfo {
        address submitter;
        uint256 startBlock;
        uint256 endBlock;
        uint256 rollupTime;
    }

    /**
     * @notice BatchInfo representing a epoch.
     *
     * @custom:field submitter     submitter
     * @custom:field startTime     epoch start time
     * @custom:field endTime       epoch end time
     */
    struct EpochInfo {
        address submitter;
        uint256 startTime;
        uint256 endTime;
    }
}
