version: '3.8'

volumes:
  sequencer_geth_data:
  sequencer_node_data:

services:
  sequencer_geth:
    image: morph/l2geth:latest
    ports:
      - "8545:8545"
      - "8546:8546"
      - "8551:8551"
      - "30303:30303"
    healthcheck:
      test: curl -f http://localhost:8545
      interval: 30s
      timeout: 5s
      retries: 3
    volumes:
      - "sequencer_geth_data:${GETH_DATA_DIR}"
      - "${PWD}/jwt-secret.txt:${JWT_SECRET_PATH}"
      - "${PWD}/genesis_geth.json:${GENESIS_FILE_PATH}"
    entrypoint: # pass the L2 specific flags by overriding the entry-point and adding extra arguments
      - "/bin/bash"
      - "/entrypoint.sh"

  sequencer_node:
    depends_on:
      sequencer_geth:
        condition: service_started
    build:
      context: ..
      dockerfile: ./ops-morph/Dockerfile
    image: morph-node:latest
    ports:
      - "26656:26656"
    environment:
      - EMPTY_BLOCK_DELAY=true
      - MORPH_NODE_L2_ETH_RPC=http://sequencer_geth:8545
      - MORPH_NODE_L2_ENGINE_RPC=http://sequencer_geth:8551
      - MORPH_NODE_L2_ENGINE_AUTH=jwt-secret.txt
      ## todo need to replace it to a public network
      - MORPH_NODE_L1_ETH_RPC=${L1_ETH_RPC}
      - MORPH_NODE_SYNC_DEPOSIT_CONTRACT_ADDRESS=0x6900000000000000000000000000000000000001
      ## - MORPH_NODE_SYNC_START_HEIGHT=88854536
    volumes:
      - "sequencer_node_data:${NODE_DATA_DIR}"
      - "${PWD}/jwt-secret.txt:${JWT_SECRET_PATH}"
    command: >
      morphnode
      --dev-sequencer
      --home $NODE_DATA_DIR

  tx-submitter:
    depends_on:
      sequencer_geth:
        condition: service_started
      sequencer_node:
        condition: service_started
    image: tx-submitter:latest
    command: rollup
    environment:
      - TX_SUBMITTER_L1_PRIVATE_KEY=ac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80
      - TX_SUBMITTER_L2_RPC_URL=http://sequencer_geth:8545
      - TX_SUBMITTER_L1_RPC_URL=${L1_ETH_RPC}
      - TX_SUBMITTER_ROLLUP_CONTRACT_ADDRESS=0x6900000000000000000000000000000000000010
      - TX_SUBMITTER_EVENT_NAME=SubmitBatches
      - TX_SUBMITTER_ROLLUP_FUNC_NAME=SubmitBatches
      - TX_SUBMITTER_BATCH_BLOCK_NUM=1
      - TX_SUBMITTER_BATCH_NUM=1
      - TX_SUBMITTER_FIRST_TIME=true
      - TX_SUBMITTER_CHAIN_ID=900