[package]
name = "prover-utils"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
anyhow = { workspace = true }
alloy-provider = { workspace = true }
alloy-network = { workspace = true }
alloy-json-rpc = { workspace = true }
serde = { workspace = true, features = ["derive"] }
log = { workspace = true }
serde_json = { workspace = true }
