# Pull Geth into a second stage deploy alpine container
FROM alpine:latest

ENV TZ Asia/Shanghai

RUN apk add tzdata && cp /usr/share/zoneinfo/${TZ} /etc/localtime \
    && echo ${TZ} > /etc/timezone

RUN apk add --no-cache ca-certificates
COPY /tx-submitter /usr/local/bin

CMD ["tx-submitter"]
