name: Deployer

on:
    push:
        branches:
            - main
        paths:
            - "build/**"
            - "bindings/**"
            - "node/**"
            - "ops/l2-genesis/**"
            - ".github/workflows/deployer.yaml"
    pull_request:
        paths:
            - "build/**"
            - "bindings/**"
            - "node/**"
            - "ops/l2-genesis/**"
            - ".github/workflows/deployer.yaml"

defaults:
    run:
        working-directory: "ops/l2-genesis"

jobs:
    check:
        if: github.event.pull_request.draft == false
        runs-on: ubuntu-latest
        steps:
            - name: Install Go
              uses: actions/setup-go@v5
              with:
                  go-version: 1.22.x
            - name: Checkout code
              uses: actions/checkout@v3
            - name: Lint
              run: |
                  rm -rf $HOME/.cache/golangci-lint
                  make lint
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Install Go
              uses: actions/setup-go@v5
              with:
                  go-version: 1.22.x
            - name: Checkout code
              uses: actions/checkout@v3
            - name: Run tests
              run: make test
