name: Prover

on:
    push:
        branches:
            - main
        paths:
            - "node/derivation/testdata/rollup_calldata_fixtures.json"
            - "prover/**"
            - ".github/workflows/prover.yml"
    pull_request:
        paths:
            - "node/derivation/testdata/rollup_calldata_fixtures.json"
            - "prover/**"
            - ".github/workflows/prover.yml"

permissions:
    contents: read

defaults:
    run:
        working-directory: "prover"

jobs:
    fmt:
        name: fmt
        runs-on: ubuntu-latest
        timeout-minutes: 30
        steps:
            - uses: actions/checkout@v4
            - uses: dtolnay/rust-toolchain@master
              with:
                  toolchain: nightly-2024-07-07
                  components: rustfmt
            - name: Check shadow-prove formatting
              run: cargo +nightly-2024-07-07 fmt --package shadow-proving --check
            - name: Check challenge formatting
              run: >-
                  cargo +nightly-2024-07-07 fmt
                  --manifest-path bin/challenge/Cargo.toml
                  --check

    build:
        name: build
        runs-on: ubuntu-latest
        timeout-minutes: 60
        steps:
            - uses: actions/checkout@v4
            - uses: dtolnay/rust-toolchain@master
              with:
                  toolchain: 1.91.0
            - name: Build shadow-prove
              run: make build-shadow-prove
            - name: Test shadow-prove
              run: cargo test --manifest-path bin/shadow-prove/Cargo.toml
            - name: Build challenge
              run: make build-challenge
            - name: Test challenge
              run: cargo test --manifest-path bin/challenge/Cargo.toml
