version: '3.4'

volumes:
  l1_geth_data:
  postgres_data:
  morph_data_0:
  morph_data_1:
  morph_data_2:
  morph_data_3:
  sentry_geth_data:
  node_data_0:
  node_data_1:
  node_data_2:
  node_data_3:
  sentry_node_data:
  validator_geth_data:
  validator_node_data:

services:
  l1:
    container_name: l1-geth
    build:
      context: ../..
      dockerfile: ops/docker/Dockerfile.l1
    image: morph-l1:latest
    ports:
      - "9545:8545"
      - "9546:8546"
      - "7060:6060"
    volumes:
      - "l1_geth_data:/db"
      - "${PWD}/jwt-secret.txt:/config/jwt-secret.txt"
      - "${PWD}/../L2-genesis/.devnet/genesis-l1.json:/genesis.json"

  morph-geth-0:
    container_name: morph-geth-0
    depends_on:
      l1:
        condition: service_started
    image: morph-geth:latest
    build:
      context: ../..
      dockerfile: ops/docker/Dockerfile.l2-geth
      target: ${BUILD_GETH}
    restart: unless-stopped
    ports:
      - "8545:8545"
      - "8546:8546"
      - "8551"
      - "6060"
      - "30303"
    volumes:
      - "morph_data_0:/db"
      - "${PWD}/jwt-secret.txt:/jwt-secret.txt"
      - "${PWD}/../L2-genesis/.devnet/genesis-l2.json:/genesis.json"
      - "${PWD}/nodekey0:/db/geth/nodekey"
    environment:
      - RUST_LOG=${RUST_LOG}
    entrypoint:
      - "/bin/bash"
      - "/entrypoint.sh"

  morph-geth-1:
    container_name: morph-geth-1
    depends_on:
      - morph-geth-0
    image: morph-geth:latest
    restart: unless-stopped
    ports:
      - "8645:8545"
      - "8646:8546"
      - "8551"
      - "6060"
      - "30303"
    volumes:
      - "morph_data_1:/db"
      - "${PWD}/jwt-secret.txt:/jwt-secret.txt"
      - "${PWD}/../L2-genesis/.devnet/genesis-l2.json:/genesis.json"
      - "${PWD}/nodekey1:/db/geth/nodekey"
      - "${PWD}/static-nodes.json:/db/geth/static-nodes.json"
    environment:
      - RUST_LOG=${RUST_LOG}
    entrypoint:
      - "/bin/bash"
      - "/entrypoint.sh"

  morph-geth-2:
    container_name: morph-geth-2
    depends_on:
      - morph-geth-0
    image: morph-geth:latest
    restart: unless-stopped
    ports:
      - "8745:8545"
      - "8746:8546"
      - "8551"
      - "6060"
      - "30303"
    volumes:
      - "morph_data_2:/db"
      - "${PWD}/jwt-secret.txt:/jwt-secret.txt"
      - "${PWD}/../L2-genesis/.devnet/genesis-l2.json:/genesis.json"
      - "${PWD}/nodekey2:/db/geth/nodekey"
      - "${PWD}/static-nodes.json:/db/geth/static-nodes.json"
    environment:
      - RUST_LOG=${RUST_LOG}
    entrypoint:
      - "/bin/bash"
      - "/entrypoint.sh"

  morph-geth-3:
    container_name: morph-geth-3
    depends_on:
      - morph-geth-0
    image: morph-geth:latest
    restart: unless-stopped
    ports:
      - "8845:8545"
      - "8846:8546"
      - "8551"
      - "6060"
      - "30303"
    volumes:
      - "morph_data_3:/db"
      - "${PWD}/jwt-secret.txt:/jwt-secret.txt"
      - "${PWD}/../L2-genesis/.devnet/genesis-l2.json:/genesis.json"
      - "${PWD}/nodekey3:/db/geth/nodekey"
      - "${PWD}/static-nodes.json:/db/geth/static-nodes.json"
    environment:
      - RUST_LOG=${RUST_LOG}
    entrypoint:
      - "/bin/bash"
      - "/entrypoint.sh"


  node-0:
    container_name: node-0
    depends_on:
      morph-geth-0:
        condition: service_started
    image: morph-node-0:latest
    build:
      context: ../..
      dockerfile: ops/docker/Dockerfile.l2-node-4
      target: node0
    restart: unless-stopped
    ports:
      - "26656"
      - "26657:26657"
      - "26658"
      - "26660"
    environment:
      - MORPH_NODE_L2_ETH_RPC=http://morph-geth-0:8545
      - MORPH_NODE_L2_ENGINE_RPC=http://morph-geth-0:8551
      - MORPH_NODE_L2_ENGINE_AUTH=jwt-secret.txt
      - MORPH_NODE_L1_ETH_RPC=${L1_ETH_RPC}
      - MORPH_NODE_SYNC_DEPOSIT_CONTRACT_ADDRESS=${MORPH_PORTAL:-0x6900000000000000000000000000000000000001}
      - MORPH_NODE_L1_CONFIRMATIONS=0
      - MORPH_NODE_SYNC_START_HEIGHT=${MORPH_NODE_SYNC_START_HEIGHT:-1}
    volumes:
      - "node_data_0:${NODE_DATA_DIR}"
      - "${PWD}/jwt-secret.txt:${JWT_SECRET_PATH}"
    command: >
      morphnode
      --home $NODE_DATA_DIR

  node-1:
    container_name: node-1
    depends_on:
      morph-geth-1:
        condition: service_started
      node-0:
        condition: service_started
    image: morph-node-1:latest
    build:
      context: ../..
      dockerfile: ops/docker/Dockerfile.l2-node-4
      target: node1
    restart: unless-stopped
    ports:
      - "26656"
      - "26657"
      - "26658"
      - "26660"
    environment:
      - MORPH_NODE_L2_ETH_RPC=http://morph-geth-1:8545
      - MORPH_NODE_L2_ENGINE_RPC=http://morph-geth-1:8551
      - MORPH_NODE_L2_ENGINE_AUTH=jwt-secret.txt
      - MORPH_NODE_L1_ETH_RPC=${L1_ETH_RPC}
      - MORPH_NODE_SYNC_DEPOSIT_CONTRACT_ADDRESS=${MORPH_PORTAL:-0x6900000000000000000000000000000000000001}
      - MORPH_NODE_L1_CONFIRMATIONS=0
      - MORPH_NODE_SYNC_START_HEIGHT=${MORPH_NODE_SYNC_START_HEIGHT:-1}
    volumes:
      - "node_data_1:${NODE_DATA_DIR}"
      - "${PWD}/jwt-secret.txt:${JWT_SECRET_PATH}"
    command: >
      morphnode
      --home $NODE_DATA_DIR

  node-2:
    container_name: node-2
    depends_on:
      morph-geth-2:
        condition: service_started
      node-0:
        condition: service_started
    image: morph-node-2:latest
    build:
      context: ../..
      dockerfile: ops/docker/Dockerfile.l2-node-4
      target: node2
    restart: unless-stopped
    ports:
      - "26656"
      - "26657"
      - "26658"
      - "26660"
    environment:
      - EMPTY_BLOCK_DELAY=true
      - MORPH_NODE_L2_ETH_RPC=http://morph-geth-2:8545
      - MORPH_NODE_L2_ENGINE_RPC=http://morph-geth-2:8551
      - MORPH_NODE_L2_ENGINE_AUTH=jwt-secret.txt
      - MORPH_NODE_L1_ETH_RPC=${L1_ETH_RPC}
      - MORPH_NODE_SYNC_DEPOSIT_CONTRACT_ADDRESS=${MORPH_PORTAL:-0x6900000000000000000000000000000000000001}
      - MORPH_NODE_L1_CONFIRMATIONS=0
      - MORPH_NODE_SYNC_START_HEIGHT=${MORPH_NODE_SYNC_START_HEIGHT:-1}
    volumes:
      - "node_data_2:${NODE_DATA_DIR}"
      - "${PWD}/jwt-secret.txt:${JWT_SECRET_PATH}"
    command: >
      morphnode
      --home $NODE_DATA_DIR

  node-3:
    container_name: node-3
    depends_on:
      morph-geth-3:
        condition: service_started
      node-0:
        condition: service_started
    image: morph-node-3:latest
    build:
      context: ../..
      dockerfile: ops/docker/Dockerfile.l2-node-4
      target: node3
    restart: unless-stopped
    ports:
      - "26656"
      - "26657"
      - "26658"
      - "26660"
    environment:
      - EMPTY_BLOCK_DELAY=true
      - MORPH_NODE_L2_ETH_RPC=http://morph-geth-3:8545
      - MORPH_NODE_L2_ENGINE_RPC=http://morph-geth-3:8551
      - MORPH_NODE_L2_ENGINE_AUTH=jwt-secret.txt
      - MORPH_NODE_L1_ETH_RPC=${L1_ETH_RPC}
      - MORPH_NODE_SYNC_DEPOSIT_CONTRACT_ADDRESS=${MORPH_PORTAL:-0x6900000000000000000000000000000000000001}
      - MORPH_NODE_L1_CONFIRMATIONS=0
      - MORPH_NODE_SYNC_START_HEIGHT=${MORPH_NODE_SYNC_START_HEIGHT:-1}
    volumes:
      - "node_data_3:${NODE_DATA_DIR}"
      - "${PWD}/jwt-secret.txt:${JWT_SECRET_PATH}"
    command: >
      morphnode
      --home $NODE_DATA_DIR

  sentry-geth-0:
    container_name: sentry-geth-0
    depends_on:
      node-3:
        condition: service_started
    image: sentry-geth:latest
    build:
      context: ../..
      dockerfile: ops/docker/Dockerfile.l2-geth-sentry
    restart: unless-stopped
    ports:
      - "8945:8545"
      - "8946:8546"
      - "8551"
      - "6060"
      - "30303"
    volumes:
      - "sentry_geth_data:/db"
      - "${PWD}/jwt-secret.txt:/jwt-secret.txt"
      - "${PWD}/../L2-genesis/.devnet/genesis-l2.json:/genesis.json"
      - "${PWD}/static-nodes.json:/db/geth/static-nodes.json"
    entrypoint:
      - "/bin/sh"
      - "/entrypoint.sh"

  sentry-node-0:
    container_name: sentry-node-0
    depends_on:
      sentry-geth-0:
        condition: service_started
    image: sentry-node-0:latest
    build:
      context: ../..
      dockerfile: ops/docker/Dockerfile.l2-node-4
      target: sentry0
    restart: unless-stopped
    ports:
      - "26656"
      - "26657"
      - "26658"
      - "26660"
    environment:
      - EMPTY_BLOCK_DELAY=true
      - MORPH_NODE_L2_ETH_RPC=http://sentry-geth-0:8545
      - MORPH_NODE_L2_ENGINE_RPC=http://sentry-geth-0:8551
      - MORPH_NODE_L2_ENGINE_AUTH=jwt-secret.txt
      - MORPH_NODE_L1_ETH_RPC=${L1_ETH_RPC}
      - MORPH_NODE_SYNC_DEPOSIT_CONTRACT_ADDRESS=${MORPH_PORTAL:-0x6900000000000000000000000000000000000001}
      - MORPH_NODE_L1_CONFIRMATIONS=0
      - MORPH_NODE_SYNC_START_HEIGHT=${MORPH_NODE_SYNC_START_HEIGHT:-1}
    volumes:
      - "sentry_node_data:${NODE_DATA_DIR}"
      - "${PWD}/jwt-secret.txt:${JWT_SECRET_PATH}"
    command: >
      morphnode
      --home $NODE_DATA_DIR    
    

  validator_geth:
    container_name: validator_geth
    image: sentry-geth:latest
    depends_on:
      tx-submitter:
        condition: service_started
    ports:
      - "7545:8545"
      - "7546:8546"
      - "7551:8551"
    healthcheck:
      test: curl -f http://localhost:8545
      interval: 30s
      timeout: 5s
      retries: 3
    volumes:
      - "validator_geth_data:${GETH_DATA_DIR}"
      - "${PWD}/jwt-secret.txt:${JWT_SECRET_PATH}"
      - "${PWD}/../L2-genesis/.devnet/genesis-l2.json:/genesis.json"
    entrypoint: # pass the L2 specific flags by overriding the entry-point and adding extra arguments
      - "/bin/bash"
      - "/entrypoint.sh"

  validator_node:
    container_name: validator_node
    depends_on:
      tx-submitter:
        condition: service_started
    build:
      context: ../..
      dockerfile: ops/docker/Dockerfile.l2-node-1
    image: morph-node:latest
    ports:
      - "26660"
    environment:
      - MORPH_NODE_L2_ETH_RPC=http://validator_geth:8545
      - MORPH_NODE_L2_ENGINE_RPC=http://validator_geth:8551
      - MORPH_NODE_L2_ENGINE_AUTH=jwt-secret.txt
      ## todo need to replace it to a public network
      - MORPH_NODE_L1_ETH_RPC=${L1_ETH_RPC}
      - MORPH_NODE_SYNC_DEPOSIT_CONTRACT_ADDRESS=${MORPH_PORTAL:-0x6900000000000000000000000000000000000001}
      - MORPH_NODE_VALIDATOR_PRIVATE_KEY=ac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80
      - MORPH_NODE_ROLLUP_ADDRESS=${MORPH_ROLLUP:-0x6900000000000000000000000000000000000010}
      - MORPH_NODE_DERIVATION_START_HEIGHT=1
      - MORPH_NODE_SYNC_START_HEIGHT=1
      - MORPH_NODE_DERIVATION_FETCH_BLOCK_RANGE=5000
      - MORPH_NODE_L1_CHAIN_ID=900
      - MORPH_NODE_VALIDATOR=true
      - MORPH_NODE_MOCK_SEQUENCER=false
      - MORPH_NODE_L1_CONFIRMATIONS=1
      - MORPH_NODE_METRICS_SERVER_ENABLE=true
      - MORPH_NODE_METRICS_PORT=26660
    volumes:
      - "validator_node_data:${NODE_DATA_DIR}"
      - "${PWD}/jwt-secret.txt:${JWT_SECRET_PATH}"
    command: >
      morphnode
      --validator
      --home $NODE_DATA_DIR

  tx-submitter:
    container_name: tx-submitter
    depends_on:
      indexer:
        condition: service_started
    build:
      context: ../..
      dockerfile: ops/docker/Dockerfile.submitter
    image: morph-tx-submitter:latest
    restart: unless-stopped
    command: tx-submitter
    ports:
      - "8060:6060"
    environment:
      # change the env variables to your own
      - TX_SUBMITTER_BUILD_ENV=dev
      - TX_SUBMITTER_L1_ETH_RPC=${L1_ETH_RPC}
      - TX_SUBMITTER_L1_PRIVATE_KEY=59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d
      - TX_SUBMITTER_L2_ETH_RPCS=http://morph-geth-0:8545,http://morph-geth-1:8545,http://morph-geth-2:8545,http://morph-geth-3:8545
      - TX_SUBMITTER_MAX_BATCH_BUILD_TIME=60s
      - TX_SUBMITTER_MAX_TX_SIZE=125952
      - TX_SUBMITTER_POLL_INTERVAL=3s
      - TX_SUBMITTER_SAFE_MINIMUM_ETHER_BALANCE=1
      - TX_SUBMITTER_TX_TIMEOUT=60s
      - TX_SUBMITTER_ROLLUP_ADDRESS=${MORPH_ROLLUP:-0x6900000000000000000000000000000000000010}
      - TX_SUBMITTER_NETWORK_TIMEOUT=20s
      - TX_SUBMITTER_MAX_BLOCK=1000
      - TX_SUBMITTER_MIN_BLOCK=50
      - TX_SUBMITTER_L2_SUBMITTER_ADDRESS=0x5300000000000000000000000000000000000005
      - TX_SUBMITTER_FINALIZE=true
      - TX_SUBMITTER_MAX_FINALIZE_NUM=100
      - TX_SUBMITTER_PRIORITY_ROLLUP=true
      - TX_SUBMITTER_METRICS_SERVER_ENABLE=true
      - TX_SUBMITTER_METRICS_HOSTNAME="0.0.0.0"
      - TX_SUBMITTER_METRICS_PORT=6060

  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=db_username
      - POSTGRES_PASSWORD=db_password
      - POSTGRES_DB=db_name
      - PGDATA=/data/postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -q -U db_username -d db_name" ]
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/data/postgres

  indexer:
    container_name: indexer
    depends_on:
      node-3:
        condition: service_started
      postgres:
        condition: service_healthy
    build:
      context: ../..
      dockerfile: ops/docker/Dockerfile.indexer
    image: morph-indexer:latest
    healthcheck:
      test: wget localhost:8080/healthz -q -O - > /dev/null 2>&1
    environment:
      # Note that you must index goerli with INDEXER_BEDROCK=false first, then
      # reindex with INDEXER_BEDROCK=true or seed the database
      - INDEXER_BEDROCK=${INDEXER_BEDROCK_GOERLI:-true}
      - INDEXER_BUILD_ENV=${INDEXER_BUILD_ENV:-development}
      - DB_PORT=${DB_PORT:-5432}
      - DB_USER=${DB_USER:-db_username}
      - DB_PASSWORD=${DB_PASSWORD:-db_password}
      - DB_NAME=${DB_NAME:-db_name}
      - DB_HOST=${DB_HOST:-postgres}
      - INDEXER_CHAIN_ID=${INDEXER_CHAIN_ID:-900}
      - INDEXER_L1_ETH_RPC=${L1_ETH_RPC}
      - INDEXER_L2_ETH_RPC=http://morph-geth-0:8545
      - INDEXER_START_BLOCK_NUMBER=0
      - INDEXER_REST_HOSTNAME=0.0.0.0
      - INDEXER_REST_PORT=8080
      - INDEXER_L1_CONF_DEPTH=1
      - INDEXER_L2_CONF_DEPTH=1
      - INDEXER_NETWORK=devnet
      - INDEXER_BEDROCK_L1_STANDARD_BRIDGE=${MORPH_STANDARD_BRIDGE:-0x6900000000000000000000000000000000000003}
      - INDEXER_BEDROCK_MORPH_PORTAL=${MORPH_PORTAL:-0x6900000000000000000000000000000000000001}
      - INDEXER_BEDROCK_ROLLUP=${MORPH_ROLLUP:-0x6900000000000000000000000000000000000010}
      - INDEXER_L1_ADDRESS_MANAGER_ADDRESS=${MORPH_ADDRESS_MANAGER:-0x6900000000000000000000000000000000000005}
      - INDEXER_BEDROCK_L1_CROSS_DOMAIN_MESSENGER=${L1_CROSS_DOMAIN_MESSENGER:-0xcf7ed3acca5a467e9e704c703e8d87f634fb0fc9}
    ports:
      - "8081:8080"

  indexer-read:
    container_name: indexer_read
    depends_on:
      indexer:
        condition: service_healthy
    build:
      context: ../..
      dockerfile: ops/docker/Dockerfile.indexer
    image: morph-indexer:latest
    healthcheck:
      test: wget localhost:8080/healthz -q -O - > /dev/null 2>&1
    environment:
      # Note that you must index goerli with INDEXER_BEDROCK=false first, then
      # reindex with INDEXER_BEDROCK=true or seed the database
      - INDEXER_BEDROCK=${INDEXER_BEDROCK_GOERLI:-true}
      - INDEXER_BUILD_ENV=${INDEXER_BUILD_ENV:-development}
      - DB_PORT=${DB_PORT:-5432}
      - DB_USER=${DB_USER:-db_username}
      - DB_PASSWORD=${DB_PASSWORD:-db_password}
      - DB_NAME=${DB_NAME:-db_name}
      - DB_HOST=${DB_HOST:-postgres}
      - INDEXER_CHAIN_ID=${INDEXER_CHAIN_ID:-900}
      - INDEXER_L1_ETH_RPC=${L1_ETH_RPC}
      - INDEXER_L2_ETH_RPC=http://morph-geth-0:8545
      - INDEXER_START_BLOCK_NUMBER=0
      - INDEXER_REST_HOSTNAME=0.0.0.0
      - INDEXER_REST_PORT=8080
      - INDEXER_L1_CONF_DEPTH=1
      - INDEXER_L2_CONF_DEPTH=1
      - INDEXER_NETWORK=devnet
      - INDEXER_DISABLE_INDEXER=true
      - INDEXER_BEDROCK_L1_STANDARD_BRIDGE=${MORPH_STANDARD_BRIDGE:-0x6900000000000000000000000000000000000003}
      - INDEXER_BEDROCK_MORPH_PORTAL=${MORPH_PORTAL:-0x6900000000000000000000000000000000000001}
      - INDEXER_BEDROCK_ROLLUP=${MORPH_ROLLUP:-0x6900000000000000000000000000000000000010}
      - INDEXER_L1_ADDRESS_MANAGER_ADDRESS=${MORPH_ADDRESS_MANAGER:-0x6900000000000000000000000000000000000005}
      - INDEXER_BEDROCK_L1_CROSS_DOMAIN_MESSENGER=${L1_CROSS_DOMAIN_MESSENGER:-0xcf7ed3acca5a467e9e704c703e8d87f634fb0fc9}
    ports:
      - "8080:8080"

  gas-price-oracle:
    container_name: gas-price-oracle
    depends_on:
      node-3:
        condition: service_started
    build:
      context: ../..
      dockerfile: ops/docker/Dockerfile.oracle
    image: morph-oracle:latest
    restart: unless-stopped
    ports:
      - "6070:6060"
    command: >
      ./app
    environment:
      - L1_RPC=${L1_ETH_RPC}
      - L2_RPC=http://morph-geth-0:8545
      - GAS_THRESHOLD=5
      - INTERVAL=5000
      - L2_GAS_PRICE_ORACLE=0x530000000000000000000000000000000000000F
      - L2_GAS_ORACLE_PRIVATE_KEY=0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80
      - OVERHEAD_THRESHOLD=200
      - OVERHEAD_INTERVAL=10
      - TXN_PER_BLOCK=1
      - TXN_PER_BATCH=50
      - L1_ROLLUP=${MORPH_ROLLUP:-0x6900000000000000000000000000000000000010}
