FROM ghcr.io/morph-l2/go-ubuntu-builder:go-1.22-ubuntu as builder

# RUN apk add --no-cache gcc musl-dev linux-headers git make

COPY . /morph

WORKDIR /morph/oracle

RUN make build

# Deploy stage using the same base image (morph/go-ubuntu-builder:go-1.22-ubuntu)
FROM ghcr.io/morph-l2/go-ubuntu-builder:go-1.22-ubuntu

# RUN apk add --no-cache ca-certificates
COPY --from=builder /morph/oracle/build/bin/staking-oracle /usr/local/bin/

CMD ["staking-oracle"]