FROM rust:1.91.0-slim as builder

RUN apt-get -qq update && apt-get -qq install -y --no-install-recommends \
    build-essential pkg-config libssl-dev && rm -rf /var/lib/apt/lists/*

COPY ./gas-oracle /gas-oracle

WORKDIR /gas-oracle
RUN cd app && cargo build --release

FROM ubuntu:22.04 as app
RUN apt-get -qq update && apt-get -qq install -y --no-install-recommends \
    ca-certificates && rm -rf /var/lib/apt/lists/*
COPY --from=builder /gas-oracle/app/target/release/app /

CMD ["./app"]
