ARG GO_BUILDER_IMAGE=ghcr.io/morph-l2/go-ubuntu-builder:go-1.24-ubuntu

# Build the transaction submitter.
FROM ${GO_BUILDER_IMAGE} AS builder

COPY . /morph

WORKDIR /morph/tx-submitter

RUN make build

# Install the transaction submitter and its runtime certificates.
FROM ${GO_BUILDER_IMAGE}

RUN apt-get -qq update \
    && apt-get -qq install -y --no-install-recommends ca-certificates \
    && rm -rf /var/lib/apt/lists/*
COPY --from=builder /morph/tx-submitter/tx-submitter /usr/local/bin/

CMD ["tx-submitter"]
