FROM rust:1.88-slim-bookworm AS builder

RUN apt-get -qq update && apt-get -qq install -y --no-install-recommends \
    pkg-config libssl-dev && rm -rf /var/lib/apt/lists/*

COPY ./gas-oracle /gas-oracle

WORKDIR /gas-oracle
RUN cd app && cargo build --release

FROM debian:bookworm-slim AS app
RUN apt-get -qq update \
    && apt-get -qq install -y --no-install-recommends bash ca-certificates libssl3 \
    && rm -rf /var/lib/apt/lists/*
COPY --from=builder /gas-oracle/app/target/release/app /

CMD ["./app"]
