# Build Geth in a stock Go builder container
FROM golang:1.22-alpine as builder

RUN apk add --no-cache gcc musl-dev linux-headers git make

COPY . /morph

WORKDIR /morph/oracle

RUN make build

# Pull Geth into a second stage deploy alpine container
FROM alpine:latest

RUN apk add --no-cache ca-certificates
COPY --from=builder /morph/oracle/build/bin/staking-oracle /usr/local/bin/

CMD ["staking-oracle"]