# Build Geth in a stock Go builder container
FROM morph/go-rust-builder:go-1.20-rust-nightly-2023-12-03 as builder

COPY . /morph

WORKDIR /morph/tx-submitter

RUN make build

# Pull Geth into a second stage deploy alpine container
FROM morph/go-rust-builder:go-1.20-rust-nightly-2023-12-03

RUN apt-get -qq update \
    && apt-get -qq install -y --no-install-recommends ca-certificates
COPY --from=builder /morph/tx-submitter/tx-submitter /usr/local/bin/

CMD ["tx-submitter"]