FROM golang:1.22-alpine as builder

RUN apk add --no-cache make gcc musl-dev linux-headers git jq bash

COPY ./bridge-backend /bridge-backend

WORKDIR /bridge-backend/indexer

RUN make

FROM alpine:latest

COPY --from=builder /bridge-backend/indexer/indexer /usr/local/bin

CMD ["indexer"]

EXPOSE 8080
